# Generated by Django 4.2.7 on 2023-11-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='vigente',
        ),
        migrations.AddField(
            model_name='owner',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
