# Generated by Django 4.2.7 on 2023-11-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='dni',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AddField(
            model_name='catalog',
            name='edad',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='catalog',
            name='nombre',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='catalog',
            name='pais',
            field=models.CharField(default='', max_length=27),
        ),
        migrations.AddField(
            model_name='catalog',
            name='vigente',
            field=models.BooleanField(default=True),
        ),
    ]
