# Generated by Django 4.2.7 on 2023-11-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_catalog_dni_catalog_edad_catalog_nombre_catalog_pais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
    ]
