# Generated by Django 4.2.7 on 2023-11-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_catalog_edad_alter_catalog_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='edad',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='nombre',
            field=models.CharField(default='', max_length=25),
        ),
    ]
