# Generated by Django 4.2.7 on 2023-11-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_catalog_edad_alter_catalog_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
